workflows:
  ios-workflow:
    name: iOS IPA Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter clean
        script: flutter clean

      - name: Get packages
        script: flutter pub get

      - name: Build IPA
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
